---
- name: Class 3 Exercise 3
  hosts: nxos
  tasks:
    - name: Gather facts
      nxos_facts:
        provider: "{{ provider_nxapi }}"
      tags: facts
     
    - name: Configure IP Addresses
      nxos_ip_interface:
        provider: "{{ provider_ssh }}"
        interface: "{{ item.interface }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        version: "{{ item.version }}"
        state: "{{ item.state|default('present') }}"
      with_items: "{{ interfaces }}"
      notify: write mem
    
    - name: Ping validation
      nxos_ping:
        provider: "{{ provider_ssh }}"
        dest: "{{ ansible_net_all_ipv4_addresses }}"
      with_nested:
        - "{{ ansible_net_all_ipv4_addresses }}"
        - "{{ interfaces }}"
      when:
        - item[1].version == 'v4'
        - item[1].addr not in item[0]
      
  handlers:
    - name: write mem
      nxos_command:
        provider: "{{ provider_ssh }}"
        commands: copy run start
        timeout: 60
      changed_when: True
