---
- name: Class 3 Exercise 1
  hosts: nxos
  tasks:
    - name: Configure VLANs
      nxos_vlan:
        provider: "{{ provider_nxapi }}"
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }}"
      with_items: "{{ vlans }}"
