---
- name: Class 3 Exercise 3
  hosts: nxos
  tasks:
    - name: Configure IP Addresses
      nxos_ip_interface:
        provider: "{{ provider_ssh }}"
        interface: "{{ item.interface }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        version: "{{ item.version }}"
        state: "{{ item.state|default('present') }}"
      with_items: "{{ interfaces }}"
      notify: write mem
    
    - name: Ping validation
      nxos_ping:
        provider: "{{ provider_ssh }}"
        dest: "{{ item.remote_addr }}"
      with: "{{ interfaces }}"
      when: item.version == 'v4'
      
  handlers:
    - name: write mem
      nxos_command:
        provider: "{{ provider_ssh }}"
        commands: copy run start
        timeout: 60
      changed_when: True
