---
- name: Gather Facts
  hosts: nxos
  gather_facts: no
  
  tasks:

    - name: Show hsrp br VLAN NXOS Command
      nxos_command:
        provider: "{{ provider_nxapi }}"
        commands: "show hsrp br"
      register: hsrp
      
#    - name: Print hsrp output
#      debug:
#        var: hsrp

    - name: HSRP Table set fact
      set_fact:
        hsrp_table: "{{ hsrp.stdout_lines[0].TABLE_grp_detail }}"
      ignore_errors: yes

    - name: Print HSRP Table
      debug:
        var: hsrp_table

#    - name: Delete File
#      file:
#        path: ./gateways.txt
#        state: absent

    - name: Print Interface Name
      debug:
        var: item.sh_vip
      with_items: "{{ hsrp_table.ROW_grp_detail }}"
      when: item.sh_group_state == "Initial"
      ignore_errors: yes

#    - name: Copy to File
#      lineinfile:
#        line="{{ item.sh_if_index }}-{{ inventory_hostname }} {{ item.sh_vip }}"
#        dest=./gateways.txt
#        state=present
#        create=yes
#        insertafter=EOF
#      with_items: "{{ hsrp_table.ROW_grp_detail }}"
#      when: item.sh_group_state == "Initial"

#    - name: Gather gateway MAC
#      set_fact:
#        gateway_mac: "{{ item.hwAddress }}"
#      with_items: "{{ interface_table }}"
#      when: item.address == '10.220.88.1'
      
#    - name: Print Gateway MAC
#      debug:
#        var: gateway_mac
