---
- name: Gather Facts
  hosts: nxos
  gather_facts: no
  
  tasks:

    - name: Show cdp neighbors detail NXOS Command
      nxos_command:
        provider: "{{ provider_nxapi }}"
        commands: "show cdp neighbors detail"
      register: cdp_output
      
    - name: Print CDP output
      debug:
        var: cdp_output

#    - name: HSRP Table set fact
#      set_fact:
#        hsrp_table: "{{ hsrp.stdout_lines[0].TABLE_grp_detail }}"
#      ignore_errors: yes

#    - name: Print HSRP Table
#      debug:
#        var: hsrp_table

#    - name: Delete File
#      file:
#        path: ./gateways.txt
#        state: absent

#    - name: Print Interface Name
#      debug:
#        var: item.sh_vip
#      with_items: "{{ hsrp_table.ROW_grp_detail }}"
#      when: item.sh_group_state == "Active"
      ignore_errors: yes

#    - name: Copy to File
#      lineinfile:
#        line="{{ item.sh_if_index }}-{{ inventory_hostname }} {{ item.sh_vip }}"
#        dest=./gateways.txt
#        state=present
#        create=yes
#        insertafter=EOF
#      with_items: "{{ hsrp_table.ROW_grp_detail }}"
#      when: item.sh_group_state == "Initial"

#    - name: Gather gateway MAC
#      set_fact:
#        gateway_mac: "{{ item.hwAddress }}"
#      with_items: "{{ interface_table }}"
#      when: item.address == '10.220.88.1'
      
#    - name: Print Gateway MAC
#      debug:
#        var: gateway_mac
