---
- name: Gather Facts
  hosts: nxos
  gather_facts: no
  
  tasks:

    - name: Show hsrp br VLAN NXOS Command
      nxos_command:
        provider: "{{ provider_nxapi }}"
        commands: "show hsrp br"
      register: hsrp
      
    - name: Print hsrp output
      debug:
        var: hsrp

#    - name: Interface Table set fact
#      set_fact:
#        interface_table: "{{ show_ip_int.stdout_lines[0].TABLE_intf }}"

#    - name: Print Interface Table
#      debug:
#        var: interface_table

#    - name: Delete File
#      file:
#        path: ./dnsnames.txt
#        state: absent

#    - name: Print Interface Name
#      debug:
#        var: item.ROW_intf["intf-name"]
#      with_items: "{{ interface_table }}"

#    - name: Copy to File
#      lineinfile:
#        line="{{ item.value.intf-name }}-{{ inventory_hostname }} {{ item.value.prefix }}"
#        dest=./dnsnames.txt
#        state=present
#        create=yes
#        insertafter=EOF
#      with_items: "{{ interface_table }}"
#      when: item.value.prefix is defined

#    - name: Gather gateway MAC
#      set_fact:
#        gateway_mac: "{{ item.hwAddress }}"
#      with_items: "{{ interface_table }}"
#      when: item.address == '10.220.88.1'
      
#    - name: Print Gateway MAC
#      debug:
#        var: gateway_mac
