---
- name: Gather Facts
  hosts: nxos
  gather_facts: no
  
  tasks:
#    - name: Gather Facts
#      nxos_facts:
#        provider: "{{ provider_nxapi }}"

    - name: Show IP Int Br VLAN NXOS Command
      nxos_command:
        provider: "{{ provider_nxapi }}"
        commands: "show ip int br"
      register: show_ip_int
      
    - name: Print show arp output
      debug:
        var: show_ip_int

    - name: Interface Table set fact
      set_fact:
        interface_table: "{{ show_ip_int.stdout_lines[0].TABLE_intf }}"

    - name: Print Interface Table
      debug:
        var: interface_table

    - name: Delete File
      file:
        path: ./dnsnames.txt
        state: absent
    
    - name: Copy to File
      lineinfile:
        line="{{ item.intf-name }}-{{ inventory_hostname }} {{ item.prefix }}"
        dest=./dnsnames.txt
        state=present
        create=yes
        insertafter=EOF
      with_items: "{{ interface_table }}"
#      when: item.value.prefix is defined

#    - name: Gather gateway MAC
#      set_fact:
#        gateway_mac: "{{ item.hwAddress }}"
#      with_items: "{{ interface_table }}"
#      when: item.address == '10.220.88.1'
      
#    - name: Print Gateway MAC
#      debug:
#        var: gateway_mac
