---

- name: Print all vars
  hosts: cisco
  vars:
    ntp_server1: 20.20.20.20
    ntp_server2: 20.20.20.30
  tasks:
    - debug:
        msg: "Host: {{ansible_host}}, Local AS: {{local_as_number}}, Remote AS: {{remote_as_number}}, NTP1: {{ntp_server1}}, NTP2: {{ntp_server2}}"
