---

- name: Print all vars
  hosts: cisco
  vars:
    ntp_server1: 20.20.20.20
    ntp_server2: 20.20.20.30
  tasks:
    - debug:
        msg: "{{ansible_host}}"
        msg: "{{local_as_number}}"
        msg: "{{remote_as_number}}"
        msg: "{{ntp_server1}}"
        msg: "{{ntp_server2}}"
