---

- name: Print ansible_host var
  hosts: cisco
  tasks:
    - debug:
        msg: "{{ansible_host}}"

- name: Print local_as_number var
  hosts: cisco
  tasks:
    - debug:
        msg: "{{local_as_number}}"
