---

- name: Exercise 4 - EOS Command Module
  hosts: pynet-sw7
  gather_facts: no
  vars:
    eapi:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: eapi
      use_ssl: True
      validate_certs: no
  
  tasks:
    
    - name: Show ARP EOS Command
      eos_command:
        provider: "{{ eapi }}"
        commands: "show arp"
      register: show_arp
      
    - name: Print show arp output
      debug:
        var: show_arp

    - name: Gateway MAC set fact
      set_fact:
        mac_table: "{{ show_arp.stdout_lines.ipV4Neighbors }}"

    - name: Print MAC Table
      debug:
        var: mac_table

#    - name: Only print 10.220.88.1
#      debug:
#        var: item
#      with_items: "{{ show_arp_new }}"
#      when: '"10.220.88.1" in item'
