---

- name: Exercise 3 - IOS Command Module
  hosts: cisco
  gather_facts: no
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: ssh
  
  tasks:
    
    - name: Show ARP Command
      ios_command:
        provider: "{{ creds }}"
        commands: "show arp"
      register: show_arp
      
    - name: Print show arp output
      debug:
        msg: "{{ show_arp }}"
