---

- name: Gather and print facts
  hosts: cisco
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - name: Gather IOS facts
      ios_facts:
        provider: "{{ creds }}"
      tags: ios_facts
    - name: Print serial number
      debug:
        msg: "{{ ansible_net_serialnum }}"
