---

- name: Exercise 4 - EOS Command Module
  hosts: arista
  gather_facts: no
  vars:
    eapi:
      host: pynet-sw7
      username: "{{ username }}"
      password: "{{ password }}"
      transport: eapi
      use_ssl: True
      validate_certs: no
  
  tasks:
    
    - name: Show ARP EOS Command
      eos_command:
        provider: "{{ eapi }}"
        commands: "show arp"
      register: show_arp
      
    - name: Print show arp output
      debug:
        var: show_arp

#    - name: Show ARP set fact
#      set_fact:
#        show_arp_new: "{{ show_arp.stdout_lines[0] }}"

#    - name: Print New Show ARP Output
#      debug:
#        var: show_arp_new

#    - name: Only print 10.220.88.1
#      debug:
#        var: item
#      with_items: "{{ show_arp_new }}"
#      when: '"10.220.88.1" in item'
