---

- name: Exercise 2 - Gathering specific facts
  hosts: cisco
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  
  tasks:
    
    - name: Gather IOS facts
      ios_facts:
        provider: "{{ creds }}"
      tags:
        - task1
        - task2
        - task3
        - task4
    
    - name: Gather All IPv4 Addresses
      debug:
        var: ansible_net_all_ipv4_addresses
      when: ansible_net_all_ipv4_addresses[0] == '10.220.88.21'
      tags: task1
      
    - name: Gather Interface Names
      debug:
        msg: "{{ item.key }}"
      with_dict: "{{ansible_net_interfaces}}"
      tags: task2

    - name: Gather UP Interface Names
      debug:
        msg: "{{ item.key }}"
      with_dict: "{{ansible_net_interfaces}}"
      when: item.value.operstatus == 'up'
      tags: task3
