---

- name: Exercise 3 - IOS Command Module
  hosts: cisco
  gather_facts: no
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: ssh
  
  tasks:
    
    - name: Show ARP Command
      ios_command:
        provider: "{{ creds }}"
        commands: "show arp"
      register: show_arp
      
    - name: Print show arp output
      debug:
        var: show_arp

    - name: Show ARP set fact
      set_fact:
        show_arp_new: "{{ show_arp.stdout_lines[0] }}"

    - name: Print New Show ARP Output
      debug:
        var: show_arp_new

    - name: Only print 10.220.88.1
      debug:
        var: {{ item }}
      with_items: "{{ show_arp_new }}"
      when: "10.220.88.1" in "{{ item }}"
