---
- name: Class 5 Exercise 2
  hosts: nxos
  gather_facts: no
  
  tasks:
    - name: NAPALM Merge
      napalm_install_config:
        provider: "{{ creds }}"
        config_file: "CFGS/{{ inventory_hostname }}-merge.txt"
        commit_changes: True
        replace_config: False
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
    
    - name: NAPALM Get Interfaces
      napalm_get_facts:
        provider: "{{ creds }}"
        filter: "interfaces_ip"

    - assert:
        that: "{{ item.ipv4 }}" in ["10.20.30.40", "10.20.30.41"]
      with_items: "{{ napalm_interfaces_ip }}"

#    - name: Interfaces Set Fact
#      set_fact:
#        interfaces_ip_table: "{{ napalm_interfaces_ip[item].ipv4 }}"
#      with_items: "{{ napalm_interfaces_ip }}"
#      ignore_errors: yes
    
#    - set_fact:
#        device_ip: "{{ item }}"
#      with_items: "{{ interfaces_ip_table }}"

#    - name: Interfaces Set Fact
#      set_fact:
#        interfaces_ip_table: "{{ [napalm_interfaces_ip.item.ipv4] }}"
#      with_items: "{{ napalm_interfaces_ip }}"
#      ignore_errors: yes
    
#    - set_fact:
#        device_ip: "{{ [item.ipv4] }}"
#      with_items: "{{ interfaces_ip_table }}"

#    - assert:
#        that: device_ip in ["10.20.30.40", "10.20.30.41"]
