---
- name: Class 5 Exercise 1
  hosts: cisco
  gather_facts: no
  
  tasks:
    - name: Napalm LLDP
      napalm_get_facts:
        provider: "{{ creds }}"
        filter: "lldp_neighbors"

    - name: LLDP Simple Set Fact
      set_fact:
        lldp_table: "{{ napalm_lldp_neighbors[item][0] }}"
      with_items: "{{ napalm_lldp_neighbors }}"
      ignore_errors: yes
    
    - debug:
        var: lldp_table
