---
- name: Class 5 Exercise 1
  hosts: cisco
  gather_facts: no
  
  tasks:
    - name: Napalm LLDP
      napalm_get_facts:
        provider: "{{ creds }}"
        filter: "lldp_neighbors"
      register: lldp
    
    - name: Print CDP output
      debug:
        var: lldp
    
#    - name: LLDP Simple Set Fact
#      set_fact:
        
