---
- name: Class 5 Exercise 2
  hosts: nxos
  gather_facts: no
  
  tasks:
    - name: NAPALM Merge
      napalm_install_config:
        provider: "{{ creds }}"
        config_file: "CFGS/{{ inventory_hostname }}-merge.txt"
        commit_changes: True
        replace_config: False
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
    
    - name: NAPALM Get Interfaces
      napalm_get_facts:
        provider: "{{ creds }}"
        filter: "interfaces_ip"

    - name: Interfaces Set Fact
      set_fact:
        interfaces_ip_table: "{{ napalm_interfaces_ip[item] }}"
      with_items: "{{ napalm_interfaces_ip }}"
      ignore_errors: yes
    
    - debug:
        var: interfaces_ip_table

#    - assert:
#        that: interfaces_ip_table in ["10.20.30.40", "10.20.30.41"]
