---
- name: Configure Cisco IOS
  hosts: cisco
  gather_facts: no
  
  tasks:
    - name: Configure SNMP Contact and Location
      ios_config:
        provider: "{{ provider_ios }}"
        lines:
          - "ip address {{ snmp_contact }} {{ item.ipv4_mask }}"
          - "ipv6 address {{ item.ipv6_address }}{{ item.ipv6_mask }}"
        parents: "interface {{ item.interface }}"
        match: line
        replace: line
