---
- name: Configure Arista EOS
  hosts: pynet-sw5
  gather_facts: no
  
  tasks:
    - name: Configure VLANs
      eos_config:
        provider: "{{ provider_eapi }}"
        lines:
          - "ip address {{  }}"
        parents: "interface {{ item.interface }}"
        match: line
        replace: line
      with_items: "{{ interfaces }}"



---
- name: Class 3 Exercise 3
  hosts: nxos
  tasks:
    - name: Configure IP Addresses
      nxos_ip_interface:
        provider: "{{ provider_ssh }}"
        interface: "{{ item.interface }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        version: "{{ item.version }}"
        state: "{{ item.state|default('present') }}"
      with_items: "{{ interfaces }}"
      notify: write mem
    
    - name: Ping validation
      nxos_ping:
        provider: "{{ provider_ssh }}"
        dest: "{{ item.remote_addr }}"
      with_items: "{{ interfaces }}"
      when: item.version == 'v4'
      
  handlers:
    - name: write mem
      nxos_command:
        provider: "{{ provider_ssh }}"
        commands: copy run start
        timeout: 60
      changed_when: True
