---
- name: Class 4 Exercise 1
  hosts: pynet-sw7
  gather_facts:no
  tasks:
    - name: Configure Static Routes
      eos_config:
        provider: "{{ provider_eapi }}"
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }}"
      with_items: "{{ vlans }}"
